# Generated by Django 2.2 on 2019-04-15 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TranferBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transection_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], default='Debit', max_length=6)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Credit', to='BANK.Account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Debit', to='BANK.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('topup_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BANK.Account')),
            ],
        ),
    ]
